tdu/accounts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    #会員登録
    url(r'^create/$', views.CreateUserView.as_view(), name='create'),
    url(r'^create_done/$', views.CreateDoneView.as_view(), name='create_done'),
    url(r'^create_complete/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.CreateCompleteView.as_view(), name='create_complete'),

    #ログイン ログアウト
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

]

tdu/app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^csv_import/$', views.csv_import, name='csv_import'),
    url(r'^csv_export/$', views.csv_export, name='csv_export'),
]
 

tdu/tdu/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^regist/', include('accounts.urls', namespace="accounts")),
    url(r'^app', include('app.urls', namespace='app')),
]

tdu/accounts/models.py
from django.db import models

# Create your models here.

tdu/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

class RegisterForm(UserCreationForm):


    #Djangoデフォルトログインではusernameとpasswordでログインするため
    #今回はfirst_name をユーザーネームとして扱う
    #username = email　アドレスと考える
    #required = Trueで登録時必須にする
    first_name = forms.CharField(label="ユーザーネーム", required=True)

    class Meta:
        model = User
        fields = (
            "username","password1","password2",
            "email", "first_name",
        )



    def __init__(self, *args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'メールアドレス'

        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'ユーザーネーム'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'


    def clean_username(self):
        username = self.cleaned_data["username"]
        atmark = username.find('@')
        string = username.find("dendai.ac.jp")

        if(atmark < 0):
            raise ValidationError("正しいメールアドレスを指定してください。")

        if(atmark > string and string < 0):
            raise ValidationError("電大メールを入力してください")

        # try:
        #     validate_email(username)
        # except ValidationError:
        #     raise ValidationError("正しいメールアドレスを指定してください。")

        try:
            self.user = User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        else:
            raise ValidationError("既に存在するメールアドレスです。")


class LoginForm(AuthenticationForm):
    #ログインフォーム作成
    #username = email と考える

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'メールアドレス'

        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

tdu/accounts/views.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.template.loader import get_template
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic
from profiles.models import UserProfile

from .forms import (
    RegisterForm,
    LoginForm,

)

#ユーザー登録


class CreateUserView(generic.FormView):
    template_name = 'accounts/create.html'
    form_class = RegisterForm
    success_url = reverse_lazy('accounts:create_done')

    def form_valid(self,form):
        user = form.save(commit=False)
        user.is_active = False
        user.email = user.username
        user.save()
        current_site = get_current_site(self.request)
        domain = current_site.domain
 #       subject_template = get_template('mailtemplate/subject.txt')
        message_template = get_template('mailtemplate/message.txt')

        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': default_token_generator.make_token(user),
            'user': user,
        }


        #subject = subject_template.render(context)
        message = message_template.render(context)
        from_email = settings.EMAIL_HOST_USER
        to = [user.username]

        send_mail('ご登録ありがとうございます',
                 message,
                from_email,
                to
                  )

        return super(CreateUserView, self).form_valid(form)


class CreateDoneView(generic.TemplateView):
    template_name = "accounts/create_done.html"






class CreateCompleteView(generic.TemplateView):
    template_name = 'accounts/create_complete.html'

    def get(self, request, **kwargs):
        token = kwargs.get("token")
        uidb64 = kwargs.get("uidb64")
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user and not user.is_active and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            createprofile = UserProfile()
            createprofile.name = user.first_name
            createprofile.email = user.email
            createprofile.save()


            return super(CreateCompleteView, self).get(request, **kwargs)
        else:
            raise Http404




def login(request):
    context = {
        'template_name': 'accounts/login.html',
        'authentication_form': LoginForm
    }
    return auth_views.login(request, **context)


def logout(request):
    context = {
        'template_name': 'accounts/login.html'
    }

    return auth_views.logout(request, **context)

tdu/accounts/templates/accounts/create.html
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ登録</h1>
  </div>

　　<form action="" method="POST">
	<div class="row">
	  <div class="col-sm-10 offset-sm-1">
　　　　    <div class="card">
  　　　　    <div class="card-block">

  			<div class="row">
  			  <div class="col-xs-12">
  			    <div class="form-group">
  			  	  {{ form.username }}
  			  	  {{ form.username.errors }}
  			  	</div>
  			  </div>
  			</div>


          <div class="row">
  			  <div class="col-xs-12 col-sm-6">
  			    <div class="form-group">
  			  	  {{ form.first_name }}
  			  	</div>
  			  </div>
              </div>


  			<div class="row">
  			  <div class="col-xs-12 col-sm-6">
  			    <div class="form-group">
  			  	  {{ form.password1 }}
  			  	  {{ form.password1.errors }}
  			  	</div>
  			  </div>
   			  <div class="col-xs-12 col-sm-6">
   			    <div class="form-group">
  			  	  {{ form.password2 }}
  			  	  {{ form.password2.errors }}
  			  	</div>
  			  </div>
  			</div>
	  　　    {% csrf_token %}
	  　　    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">会員登録</button>
  　　　　    </div>
　　　　    </div>
      </div>
    </div>
　　</form>

</div>
{% endblock %}

tdu/accounts/templates/accounts/create_complete.html
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ登録</h1>
    <p class="lead">会員登録がおわりました</p>
  </div>
</div><!-- /.container -->
{% endblock %}

tdu/accounts/templates/accounts/create_done.html
{% block content %}
<div class="container">
  <div class="center">
    <h1>ユーザ登録</h1>
    <p class="lead">仮登録しました。本登録はメールをみてください</p>
  </div>
</div><!-- /.container -->
{% endblock %}

tdu/accounts/templates/accounts/login.html
{% block content %}
<div class="container">
  <div class="center">
    <h1>ログインページ</h1>
  </div>

  <div class="card-group">
    <div class="card card-outline-primary">
      <div class="card-block">
        <form action="{% url 'accounts:login' %}" method="POST">
  		  <p>{{ form.non_field_errors }}</p>
	    　　{{ form.username }}
	    　　{{ form.password }}
	  　　  {% csrf_token %}
	  	  <input type="hidden" name="next" value="{{ next }}" />
	  　　  <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
	        ログイン
	      </button>
	    </form>
      </div>
    </div>
    <div class="card card-outline-primary">
      <div class="card-block">
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'accounts:create' %}">
          会員登録
        </a>
      </div>
    </div>

  </div><!-- /.card-group -->
　　
</div><!-- /.container -->
{% endblock %}