tdu/app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^csv_import/$', views.csv_import, name='csv_import'),
    url(r'^csv_export/$', views.csv_export, name='csv_export'),
]
 

tdu/tdu/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^regist/', include('accounts.urls', namespace="accounts")),
    url(r'^app', include('app.urls', namespace='app')),
]

tdu/app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

tdu/app/templates/app/post_list.html
{% extends 'app/base.html' %}
{% block content %}
  <form action='{% url "app:csv_import" %}' method='POST' enctype="multipart/form-data">
    <h2>CSVインポート</h2>
    <input type='file' name='csv'>
    <input type="submit" value="送信する">
    {% csrf_token %}
  </form>
  <hr>
  <form action='{% url "app:csv_export" %}' method='POST' enctype="multipart/form-data">
    <h2>CSVエクスポート</h2>
    <input type="submit" value="エクスポート">
    {% csrf_token %}
  </form>
  <hr>
  <table border="1">
    <thead>
      <tr>
        <th>ID</th>
        <th>曜日</th>
        <th>時間</th>
        <th>科目名</th>
        <th>カテゴリ</th>
      </tr>
    </thead>
    <tbody>
      {% for post in post_list %}
      <tr>
        <td>{{ post.pk }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.text }}</td>
        <td>{{ post.sub }}</td>
        <td>{{ post.category.name }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}